default_stages: [pre-commit]

default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(k_srme|scripts|data)/.*\.py$
      - id: ruff-format
